export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// reading
export const REQUESTED_READING_FEEDS_LIST = 'REQUESTED_READING_FEEDS_LIST';
export const RECEIVED_READING_FEEDS_LIST = 'RECEIVED_READING_FEEDS_LIST';

// movie
export const REQUESTED_MOVIE_FEEDS_LIST = 'REQUESTED_MOVIE_FEEDS_LIST';
export const RECEIVED_MOVIE_FEEDS_LIST = 'RECEIVED_MOVIE_FEEDS_LIST';
