export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// reading
export const REQUESTED_READING_FEEDS_LIST = 'REQUESTED_READING_FEEDS_LIST';
export const RECEIVED_READING_FEEDS_LIST = 'RECEIVED_READING_FEEDS_LIST';

// movie
export const REQUESTED_MOVIE_FEEDS_LIST = 'REQUESTED_MOVIE_FEEDS_LIST';
export const RECEIVED_MOVIE_FEEDS_LIST = 'RECEIVED_MOVIE_FEEDS_LIST';

// music
export const REQUESTED_MUSIC_FEEDS_LIST = 'REQUESTED_MUSIC_FEEDS_LIST';
export const RECEIVED_MUSIC_FEEDS_LIST = 'RECEIVED_MUSIC_FEEDS_LIST';
export const REQUESTED_PLAYABLE_SONG_URL = 'REQUESTED_PLAYABLE_SONG_URL';
export const RECEIVED_PLAYABLE_SONG_URL = 'RECEIVED_PLAYABLE_SONG_URL';
export const PLAY_SINGLE_SONG = 'PLAY_SINGLE_SONG';
export const STOP_SINGLE_SONG = 'STOP_SINGLE_SONG';

// home
export const REQUESTED_HOME_FEEDS_LIST = 'REQUESTED_HOME_FEEDS_LIST';
export const RECEIVED_HOME_FEEDS_LIST = 'RECEIVED_HOME_FEEDS_LIST';
export const REQUESTED_HOME_ID_LIST = 'REQUESTED_HOME_ID_LIST';
export const RECEIVED_HOME_ID_LIST = 'RECEIVED_HOME_ID_LIST';
